// Code generated by command: go run generate.go -out distance_amd64.s -stubs stub_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func DotProductAVX2(a []float32, b []float32) float32
// Requires: AVX, FMA3, SSE
TEXT ·DotProductAVX2(SB), NOSPLIT, $0-52
	MOVQ   a_base+0(FP), AX
	MOVQ   b_base+24(FP), CX
	MOVQ   a_len+8(FP), DX
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3

dot_loop:
	CMPQ        DX, $0x20
	JL          dot_tail
	VMOVUPS     (AX), Y4
	VMOVUPS     (CX), Y5
	VFMADD231PS Y4, Y5, Y0
	VMOVUPS     32(AX), Y4
	VMOVUPS     32(CX), Y5
	VFMADD231PS Y4, Y5, Y1
	VMOVUPS     64(AX), Y4
	VMOVUPS     64(CX), Y5
	VFMADD231PS Y4, Y5, Y2
	VMOVUPS     96(AX), Y4
	VMOVUPS     96(CX), Y5
	VFMADD231PS Y4, Y5, Y3
	ADDQ        $0x80, AX
	ADDQ        $0x80, CX
	SUBQ        $0x20, DX
	JMP         dot_loop

dot_tail:
	VADDPS Y1, Y0, Y0
	VADDPS Y2, Y0, Y0
	VADDPS Y3, Y0, Y0

dot_tail_8:
	CMPQ        DX, $0x08
	JL          dot_tail_1
	VMOVUPS     (AX), Y1
	VMOVUPS     (CX), Y2
	VFMADD231PS Y1, Y2, Y0
	ADDQ        $0x20, AX
	ADDQ        $0x20, CX
	SUBQ        $0x08, DX
	JMP         dot_tail_8

dot_tail_1:
	VEXTRACTF128 $0x01, Y0, X1
	VADDPS       X1, X0, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0

dot_scalar_loop:
	CMPQ   DX, $0x00
	JE     dot_done
	VMOVSS (AX), X1
	VMOVSS (CX), X2
	VMULSS X1, X2, X1
	VADDSS X1, X0, X0
	ADDQ   $0x04, AX
	ADDQ   $0x04, CX
	SUBQ   $0x01, DX
	JMP    dot_scalar_loop

dot_done:
	MOVSS X0, ret+48(FP)
	RET

// func L2DistanceAVX2(a []float32, b []float32) float32
// Requires: AVX, FMA3, SSE
TEXT ·L2DistanceAVX2(SB), NOSPLIT, $0-52
	MOVQ   a_base+0(FP), AX
	MOVQ   b_base+24(FP), CX
	MOVQ   a_len+8(FP), DX
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3

l2_loop:
	CMPQ        DX, $0x20
	JL          l2_tail
	VMOVUPS     (AX), Y4
	VMOVUPS     (CX), Y5
	VSUBPS      Y5, Y4, Y4
	VFMADD231PS Y4, Y4, Y0
	VMOVUPS     32(AX), Y4
	VMOVUPS     32(CX), Y5
	VSUBPS      Y5, Y4, Y4
	VFMADD231PS Y4, Y4, Y1
	VMOVUPS     64(AX), Y4
	VMOVUPS     64(CX), Y5
	VSUBPS      Y5, Y4, Y4
	VFMADD231PS Y4, Y4, Y2
	VMOVUPS     96(AX), Y4
	VMOVUPS     96(CX), Y5
	VSUBPS      Y5, Y4, Y4
	VFMADD231PS Y4, Y4, Y3
	ADDQ        $0x80, AX
	ADDQ        $0x80, CX
	SUBQ        $0x20, DX
	JMP         l2_loop

l2_tail:
	VADDPS Y1, Y0, Y0
	VADDPS Y2, Y0, Y0
	VADDPS Y3, Y0, Y0

l2_tail_8:
	CMPQ        DX, $0x08
	JL          l2_tail_1
	VMOVUPS     (AX), Y1
	VMOVUPS     (CX), Y2
	VSUBPS      Y2, Y1, Y1
	VFMADD231PS Y1, Y1, Y0
	ADDQ        $0x20, AX
	ADDQ        $0x20, CX
	SUBQ        $0x08, DX
	JMP         l2_tail_8

l2_tail_1:
	VEXTRACTF128 $0x01, Y0, X1
	VADDPS       X1, X0, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0

l2_scalar_loop:
	CMPQ   DX, $0x00
	JE     l2_done
	VMOVSS (AX), X1
	VMOVSS (CX), X2
	VSUBSS X2, X1, X1
	VMULSS X1, X1, X1
	VADDSS X1, X0, X0
	ADDQ   $0x04, AX
	ADDQ   $0x04, CX
	SUBQ   $0x01, DX
	JMP    l2_scalar_loop

l2_done:
	MOVSS X0, ret+48(FP)
	RET

// func L2Distance4AVX2(q []float32, b0 []float32, b1 []float32, b2 []float32, b3 []float32) (d0 float32, d1 float32, d2 float32, d3 float32)
// Requires: AVX, FMA3, SSE
TEXT ·L2Distance4AVX2(SB), NOSPLIT, $0-136
	MOVQ   q_base+0(FP), AX
	MOVQ   b0_base+24(FP), CX
	MOVQ   b1_base+48(FP), DX
	MOVQ   b2_base+72(FP), BX
	MOVQ   b3_base+96(FP), SI
	MOVQ   q_len+8(FP), DI
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3

l2x4_loop:
	CMPQ        DI, $0x08
	JL          l2x4_tail
	VMOVUPS     (AX), Y4
	VMOVUPS     (CX), Y5
	VSUBPS      Y4, Y5, Y5
	VFMADD231PS Y5, Y5, Y0
	VMOVUPS     (DX), Y5
	VSUBPS      Y4, Y5, Y5
	VFMADD231PS Y5, Y5, Y1
	VMOVUPS     (BX), Y5
	VSUBPS      Y4, Y5, Y5
	VFMADD231PS Y5, Y5, Y2
	VMOVUPS     (SI), Y5
	VSUBPS      Y4, Y5, Y5
	VFMADD231PS Y5, Y5, Y3
	ADDQ        $0x20, AX
	ADDQ        $0x20, CX
	ADDQ        $0x20, DX
	ADDQ        $0x20, BX
	ADDQ        $0x20, SI
	SUBQ        $0x08, DI
	JMP         l2x4_loop

l2x4_tail:
	VEXTRACTF128 $0x01, Y0, X4
	VADDPS       X4, X0, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0
	VEXTRACTF128 $0x01, Y1, X4
	VADDPS       X4, X1, X1
	VHADDPS      X1, X1, X1
	VHADDPS      X1, X1, X1
	VEXTRACTF128 $0x01, Y2, X4
	VADDPS       X4, X2, X2
	VHADDPS      X2, X2, X2
	VHADDPS      X2, X2, X2
	VEXTRACTF128 $0x01, Y3, X4
	VADDPS       X4, X3, X3
	VHADDPS      X3, X3, X3
	VHADDPS      X3, X3, X3

l2x4_scalar_loop:
	CMPQ   DI, $0x00
	JE     l2x4_done
	VMOVSS (AX), X4
	VMOVSS (CX), X5
	VSUBSS X4, X5, X5
	VMULSS X5, X5, X5
	VADDSS X5, X0, X0
	VMOVSS (DX), X5
	VSUBSS X4, X5, X5
	VMULSS X5, X5, X5
	VADDSS X5, X1, X1
	VMOVSS (BX), X5
	VSUBSS X4, X5, X5
	VMULSS X5, X5, X5
	VADDSS X5, X2, X2
	VMOVSS (SI), X5
	VSUBSS X4, X5, X5
	VMULSS X5, X5, X5
	VADDSS X5, X3, X3
	ADDQ   $0x04, AX
	ADDQ   $0x04, CX
	ADDQ   $0x04, DX
	ADDQ   $0x04, BX
	ADDQ   $0x04, SI
	SUBQ   $0x01, DI
	JMP    l2x4_scalar_loop

l2x4_done:
	MOVSS X0, d0+120(FP)
	MOVSS X1, d1+124(FP)
	MOVSS X2, d2+128(FP)
	MOVSS X3, d3+132(FP)
	RET

// func l2Distance4PtrAVX2(q []float32, b0 *byte, b1 *byte, b2 *byte, b3 *byte) (d0 float32, d1 float32, d2 float32, d3 float32)
// Requires: AVX, FMA3, SSE
TEXT ·l2Distance4PtrAVX2(SB), NOSPLIT, $0-72
	MOVQ   q_base+0(FP), AX
	MOVQ   q_len+8(FP), CX
	MOVQ   b0+24(FP), DX
	MOVQ   b1+32(FP), BX
	MOVQ   b2+40(FP), SI
	MOVQ   b3+48(FP), DI
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3

l2x4ptrraw_loop:
	CMPQ        CX, $0x08
	JL          l2x4ptrraw_tail
	VMOVUPS     (AX), Y4
	VMOVUPS     (DX), Y5
	VSUBPS      Y4, Y5, Y5
	VFMADD231PS Y5, Y5, Y0
	ADDQ        $0x20, DX
	VMOVUPS     (BX), Y5
	VSUBPS      Y4, Y5, Y5
	VFMADD231PS Y5, Y5, Y1
	ADDQ        $0x20, BX
	VMOVUPS     (SI), Y5
	VSUBPS      Y4, Y5, Y5
	VFMADD231PS Y5, Y5, Y2
	ADDQ        $0x20, SI
	VMOVUPS     (DI), Y5
	VSUBPS      Y4, Y5, Y5
	VFMADD231PS Y5, Y5, Y3
	ADDQ        $0x20, DI
	ADDQ        $0x20, AX
	SUBQ        $0x08, CX
	JMP         l2x4ptrraw_loop

l2x4ptrraw_tail:
	VEXTRACTF128 $0x01, Y0, X4
	VADDPS       X4, X0, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0
	VEXTRACTF128 $0x01, Y1, X4
	VADDPS       X4, X1, X1
	VHADDPS      X1, X1, X1
	VHADDPS      X1, X1, X1
	VEXTRACTF128 $0x01, Y2, X4
	VADDPS       X4, X2, X2
	VHADDPS      X2, X2, X2
	VHADDPS      X2, X2, X2
	VEXTRACTF128 $0x01, Y3, X4
	VADDPS       X4, X3, X3
	VHADDPS      X3, X3, X3
	VHADDPS      X3, X3, X3

l2x4ptrraw_scalar_loop:
	CMPQ   CX, $0x00
	JE     l2x4ptrraw_done
	VMOVSS (AX), X4
	VMOVSS (DX), X5
	VSUBSS X4, X5, X5
	VMULSS X5, X5, X5
	VADDSS X5, X0, X0
	ADDQ   $0x04, DX
	VMOVSS (BX), X5
	VSUBSS X4, X5, X5
	VMULSS X5, X5, X5
	VADDSS X5, X1, X1
	ADDQ   $0x04, BX
	VMOVSS (SI), X5
	VSUBSS X4, X5, X5
	VMULSS X5, X5, X5
	VADDSS X5, X2, X2
	ADDQ   $0x04, SI
	VMOVSS (DI), X5
	VSUBSS X4, X5, X5
	VMULSS X5, X5, X5
	VADDSS X5, X3, X3
	ADDQ   $0x04, DI
	ADDQ   $0x04, AX
	SUBQ   $0x01, CX
	JMP    l2x4ptrraw_scalar_loop

l2x4ptrraw_done:
	MOVSS X0, d0+56(FP)
	MOVSS X1, d1+60(FP)
	MOVSS X2, d2+64(FP)
	MOVSS X3, d3+68(FP)
	RET

// func l2Distance8PtrAVX2(q []float32, b0 *byte, b1 *byte, b2 *byte, b3 *byte, b4 *byte, b5 *byte, b6 *byte, b7 *byte) (d0 float32, d1 float32, d2 float32, d3 float32, d4 float32, d5 float32, d6 float32, d7 float32)
// Requires: AVX, FMA3, SSE
TEXT ·l2Distance8PtrAVX2(SB), NOSPLIT, $0-120
	MOVQ   q_base+0(FP), AX
	MOVQ   q_len+8(FP), CX
	MOVQ   b0+24(FP), DX
	MOVQ   b1+32(FP), BX
	MOVQ   b2+40(FP), SI
	MOVQ   b3+48(FP), DI
	MOVQ   b4+56(FP), R8
	MOVQ   b5+64(FP), R9
	MOVQ   b6+72(FP), R10
	MOVQ   b7+80(FP), R11
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3
	VXORPS Y4, Y4, Y4
	VXORPS Y5, Y5, Y5
	VXORPS Y6, Y6, Y6
	VXORPS Y7, Y7, Y7

l2x8ptr_loop:
	CMPQ        CX, $0x08
	JL          l2x8ptr_tail
	VMOVUPS     (AX), Y8
	VMOVUPS     (DX), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y0
	ADDQ        $0x20, DX
	VMOVUPS     (BX), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y1
	ADDQ        $0x20, BX
	VMOVUPS     (SI), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y2
	ADDQ        $0x20, SI
	VMOVUPS     (DI), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y3
	ADDQ        $0x20, DI
	VMOVUPS     (R8), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y4
	ADDQ        $0x20, R8
	VMOVUPS     (R9), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y5
	ADDQ        $0x20, R9
	VMOVUPS     (R10), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y6
	ADDQ        $0x20, R10
	VMOVUPS     (R11), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y7
	ADDQ        $0x20, R11
	ADDQ        $0x20, AX
	SUBQ        $0x08, CX
	JMP         l2x8ptr_loop

l2x8ptr_tail:
	VEXTRACTF128 $0x01, Y0, X8
	VADDPS       X8, X0, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0
	VEXTRACTF128 $0x01, Y1, X8
	VADDPS       X8, X1, X1
	VHADDPS      X1, X1, X1
	VHADDPS      X1, X1, X1
	VEXTRACTF128 $0x01, Y2, X8
	VADDPS       X8, X2, X2
	VHADDPS      X2, X2, X2
	VHADDPS      X2, X2, X2
	VEXTRACTF128 $0x01, Y3, X8
	VADDPS       X8, X3, X3
	VHADDPS      X3, X3, X3
	VHADDPS      X3, X3, X3
	VEXTRACTF128 $0x01, Y4, X8
	VADDPS       X8, X4, X4
	VHADDPS      X4, X4, X4
	VHADDPS      X4, X4, X4
	VEXTRACTF128 $0x01, Y5, X8
	VADDPS       X8, X5, X5
	VHADDPS      X5, X5, X5
	VHADDPS      X5, X5, X5
	VEXTRACTF128 $0x01, Y6, X8
	VADDPS       X8, X6, X6
	VHADDPS      X6, X6, X6
	VHADDPS      X6, X6, X6
	VEXTRACTF128 $0x01, Y7, X8
	VADDPS       X8, X7, X7
	VHADDPS      X7, X7, X7
	VHADDPS      X7, X7, X7

l2x8ptr_scalar_loop:
	CMPQ   CX, $0x00
	JE     l2x8ptr_done
	VMOVSS (AX), X8
	VMOVSS (DX), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X0, X0
	ADDQ   $0x04, DX
	VMOVSS (BX), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X1, X1
	ADDQ   $0x04, BX
	VMOVSS (SI), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X2, X2
	ADDQ   $0x04, SI
	VMOVSS (DI), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X3, X3
	ADDQ   $0x04, DI
	VMOVSS (R8), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X4, X4
	ADDQ   $0x04, R8
	VMOVSS (R9), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X5, X5
	ADDQ   $0x04, R9
	VMOVSS (R10), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X6, X6
	ADDQ   $0x04, R10
	VMOVSS (R11), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X7, X7
	ADDQ   $0x04, R11
	ADDQ   $0x04, AX
	SUBQ   $0x01, CX
	JMP    l2x8ptr_scalar_loop

l2x8ptr_done:
	MOVSS X0, d0+88(FP)
	MOVSS X1, d1+92(FP)
	MOVSS X2, d2+96(FP)
	MOVSS X3, d3+100(FP)
	MOVSS X4, d4+104(FP)
	MOVSS X5, d5+108(FP)
	MOVSS X6, d6+112(FP)
	MOVSS X7, d7+116(FP)
	RET

// func l2AnyLessThan8PtrAVX2(q []float32, b0 *byte, b1 *byte, b2 *byte, b3 *byte, b4 *byte, b5 *byte, b6 *byte, b7 *byte, cutoff float32) uint32
// Requires: AVX, FMA3, SSE
TEXT ·l2AnyLessThan8PtrAVX2(SB), NOSPLIT, $0-100
	MOVQ   q_base+0(FP), AX
	MOVQ   q_len+8(FP), CX
	MOVQ   b0+24(FP), DX
	MOVQ   b1+32(FP), BX
	MOVQ   b2+40(FP), SI
	MOVQ   b3+48(FP), DI
	MOVQ   b4+56(FP), R8
	MOVQ   b5+64(FP), R9
	MOVQ   b6+72(FP), R10
	MOVQ   b7+80(FP), R11
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3
	VXORPS Y4, Y4, Y4
	VXORPS Y5, Y5, Y5
	VXORPS Y6, Y6, Y6
	VXORPS Y7, Y7, Y7

l2x8any_loop:
	CMPQ        CX, $0x08
	JL          l2x8any_tail
	VMOVUPS     (AX), Y8
	VMOVUPS     (DX), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y0
	ADDQ        $0x20, DX
	VMOVUPS     (BX), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y1
	ADDQ        $0x20, BX
	VMOVUPS     (SI), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y2
	ADDQ        $0x20, SI
	VMOVUPS     (DI), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y3
	ADDQ        $0x20, DI
	VMOVUPS     (R8), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y4
	ADDQ        $0x20, R8
	VMOVUPS     (R9), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y5
	ADDQ        $0x20, R9
	VMOVUPS     (R10), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y6
	ADDQ        $0x20, R10
	VMOVUPS     (R11), Y9
	VSUBPS      Y8, Y9, Y9
	VFMADD231PS Y9, Y9, Y7
	ADDQ        $0x20, R11
	ADDQ        $0x20, AX
	SUBQ        $0x08, CX
	JMP         l2x8any_loop

l2x8any_tail:
	VEXTRACTF128 $0x01, Y0, X8
	VADDPS       X8, X0, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0
	VEXTRACTF128 $0x01, Y1, X8
	VADDPS       X8, X1, X1
	VHADDPS      X1, X1, X1
	VHADDPS      X1, X1, X1
	VEXTRACTF128 $0x01, Y2, X8
	VADDPS       X8, X2, X2
	VHADDPS      X2, X2, X2
	VHADDPS      X2, X2, X2
	VEXTRACTF128 $0x01, Y3, X8
	VADDPS       X8, X3, X3
	VHADDPS      X3, X3, X3
	VHADDPS      X3, X3, X3
	VEXTRACTF128 $0x01, Y4, X8
	VADDPS       X8, X4, X4
	VHADDPS      X4, X4, X4
	VHADDPS      X4, X4, X4
	VEXTRACTF128 $0x01, Y5, X8
	VADDPS       X8, X5, X5
	VHADDPS      X5, X5, X5
	VHADDPS      X5, X5, X5
	VEXTRACTF128 $0x01, Y6, X8
	VADDPS       X8, X6, X6
	VHADDPS      X6, X6, X6
	VHADDPS      X6, X6, X6
	VEXTRACTF128 $0x01, Y7, X8
	VADDPS       X8, X7, X7
	VHADDPS      X7, X7, X7
	VHADDPS      X7, X7, X7

l2x8any_scalar_loop:
	CMPQ   CX, $0x00
	JE     l2x8any_done
	VMOVSS (AX), X8
	VMOVSS (DX), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X0, X0
	ADDQ   $0x04, DX
	VMOVSS (BX), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X1, X1
	ADDQ   $0x04, BX
	VMOVSS (SI), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X2, X2
	ADDQ   $0x04, SI
	VMOVSS (DI), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X3, X3
	ADDQ   $0x04, DI
	VMOVSS (R8), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X4, X4
	ADDQ   $0x04, R8
	VMOVSS (R9), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X5, X5
	ADDQ   $0x04, R9
	VMOVSS (R10), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X6, X6
	ADDQ   $0x04, R10
	VMOVSS (R11), X9
	VSUBSS X8, X9, X9
	VMULSS X9, X9, X9
	VADDSS X9, X7, X7
	ADDQ   $0x04, R11
	ADDQ   $0x04, AX
	SUBQ   $0x01, CX
	JMP    l2x8any_scalar_loop

l2x8any_done:
	MOVSS    cutoff+88(FP), X8
	VUCOMISS X8, X0
	JP       l2x8any_compare_next_0
	JAE      l2x8any_compare_next_0
	MOVL     $0x00000001, AX
	MOVL     AX, ret+96(FP)
	RET

l2x8any_compare_next_0:
	VUCOMISS X8, X1
	JP       l2x8any_compare_next_1
	JAE      l2x8any_compare_next_1
	MOVL     $0x00000001, AX
	MOVL     AX, ret+96(FP)
	RET

l2x8any_compare_next_1:
	VUCOMISS X8, X2
	JP       l2x8any_compare_next_2
	JAE      l2x8any_compare_next_2
	MOVL     $0x00000001, AX
	MOVL     AX, ret+96(FP)
	RET

l2x8any_compare_next_2:
	VUCOMISS X8, X3
	JP       l2x8any_compare_next_3
	JAE      l2x8any_compare_next_3
	MOVL     $0x00000001, AX
	MOVL     AX, ret+96(FP)
	RET

l2x8any_compare_next_3:
	VUCOMISS X8, X4
	JP       l2x8any_compare_next_4
	JAE      l2x8any_compare_next_4
	MOVL     $0x00000001, AX
	MOVL     AX, ret+96(FP)
	RET

l2x8any_compare_next_4:
	VUCOMISS X8, X5
	JP       l2x8any_compare_next_5
	JAE      l2x8any_compare_next_5
	MOVL     $0x00000001, AX
	MOVL     AX, ret+96(FP)
	RET

l2x8any_compare_next_5:
	VUCOMISS X8, X6
	JP       l2x8any_compare_next_6
	JAE      l2x8any_compare_next_6
	MOVL     $0x00000001, AX
	MOVL     AX, ret+96(FP)
	RET

l2x8any_compare_next_6:
	VUCOMISS X8, X7
	JP       l2x8any_compare_next_7
	JAE      l2x8any_compare_next_7
	MOVL     $0x00000001, AX
	MOVL     AX, ret+96(FP)
	RET

l2x8any_compare_next_7:
	MOVL $0x00000000, AX
	MOVL AX, ret+96(FP)
	RET

// func prefetch8L1AMD64(ptrs *[8]*byte)
// Requires: MMX+
TEXT ·prefetch8L1AMD64(SB), NOSPLIT, $0-8
	MOVQ       ptrs+0(FP), AX
	MOVQ       (AX), CX
	PREFETCHT0 (CX)
	MOVQ       8(AX), CX
	PREFETCHT0 (CX)
	MOVQ       16(AX), CX
	PREFETCHT0 (CX)
	MOVQ       24(AX), CX
	PREFETCHT0 (CX)
	MOVQ       32(AX), CX
	PREFETCHT0 (CX)
	MOVQ       40(AX), CX
	PREFETCHT0 (CX)
	MOVQ       48(AX), CX
	PREFETCHT0 (CX)
	MOVQ       56(AX), AX
	PREFETCHT0 (AX)
	RET
