// Code generated by command: go run generate.go -out distance_amd64.s -stubs stub_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func DotProductAVX2(a []float32, b []float32) float32
// Requires: AVX, FMA3, SSE
TEXT ·DotProductAVX2(SB), NOSPLIT, $0-52
	MOVQ   a_base+0(FP), AX
	MOVQ   b_base+24(FP), CX
	MOVQ   a_len+8(FP), DX
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3

dot_loop:
	CMPQ        DX, $0x20
	JL          dot_tail
	VMOVUPS     (AX), Y4
	VMOVUPS     (CX), Y5
	VFMADD231PS Y4, Y5, Y0
	VMOVUPS     32(AX), Y4
	VMOVUPS     32(CX), Y5
	VFMADD231PS Y4, Y5, Y1
	VMOVUPS     64(AX), Y4
	VMOVUPS     64(CX), Y5
	VFMADD231PS Y4, Y5, Y2
	VMOVUPS     96(AX), Y4
	VMOVUPS     96(CX), Y5
	VFMADD231PS Y4, Y5, Y3
	ADDQ        $0x80, AX
	ADDQ        $0x80, CX
	SUBQ        $0x20, DX
	JMP         dot_loop

dot_tail:
	VADDPS Y1, Y0, Y0
	VADDPS Y2, Y0, Y0
	VADDPS Y3, Y0, Y0

dot_tail_8:
	CMPQ        DX, $0x08
	JL          dot_tail_1
	VMOVUPS     (AX), Y1
	VMOVUPS     (CX), Y2
	VFMADD231PS Y1, Y2, Y0
	ADDQ        $0x20, AX
	ADDQ        $0x20, CX
	SUBQ        $0x08, DX
	JMP         dot_tail_8

dot_tail_1:
	VEXTRACTF128 $0x01, Y0, X1
	VADDPS       X1, X0, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0

dot_scalar_loop:
	CMPQ   DX, $0x00
	JE     dot_done
	VMOVSS (AX), X1
	VMOVSS (CX), X2
	VMULSS X1, X2, X1
	VADDSS X1, X0, X0
	ADDQ   $0x04, AX
	ADDQ   $0x04, CX
	SUBQ   $0x01, DX
	JMP    dot_scalar_loop

dot_done:
	MOVSS X0, ret+48(FP)
	RET

// func L2DistanceAVX2(a []float32, b []float32) float32
// Requires: AVX, FMA3, SSE
TEXT ·L2DistanceAVX2(SB), NOSPLIT, $0-52
	MOVQ   a_base+0(FP), AX
	MOVQ   b_base+24(FP), CX
	MOVQ   a_len+8(FP), DX
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3

l2_loop:
	CMPQ        DX, $0x20
	JL          l2_tail
	VMOVUPS     (AX), Y4
	VMOVUPS     (CX), Y5
	VSUBPS      Y5, Y4, Y4
	VFMADD231PS Y4, Y4, Y0
	VMOVUPS     32(AX), Y4
	VMOVUPS     32(CX), Y5
	VSUBPS      Y5, Y4, Y4
	VFMADD231PS Y4, Y4, Y1
	VMOVUPS     64(AX), Y4
	VMOVUPS     64(CX), Y5
	VSUBPS      Y5, Y4, Y4
	VFMADD231PS Y4, Y4, Y2
	VMOVUPS     96(AX), Y4
	VMOVUPS     96(CX), Y5
	VSUBPS      Y5, Y4, Y4
	VFMADD231PS Y4, Y4, Y3
	ADDQ        $0x80, AX
	ADDQ        $0x80, CX
	SUBQ        $0x20, DX
	JMP         l2_loop

l2_tail:
	VADDPS Y1, Y0, Y0
	VADDPS Y2, Y0, Y0
	VADDPS Y3, Y0, Y0

l2_tail_8:
	CMPQ        DX, $0x08
	JL          l2_tail_1
	VMOVUPS     (AX), Y1
	VMOVUPS     (CX), Y2
	VSUBPS      Y2, Y1, Y1
	VFMADD231PS Y1, Y1, Y0
	ADDQ        $0x20, AX
	ADDQ        $0x20, CX
	SUBQ        $0x08, DX
	JMP         l2_tail_8

l2_tail_1:
	VEXTRACTF128 $0x01, Y0, X1
	VADDPS       X1, X0, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0

l2_scalar_loop:
	CMPQ   DX, $0x00
	JE     l2_done
	VMOVSS (AX), X1
	VMOVSS (CX), X2
	VSUBSS X2, X1, X1
	VMULSS X1, X1, X1
	VADDSS X1, X0, X0
	ADDQ   $0x04, AX
	ADDQ   $0x04, CX
	SUBQ   $0x01, DX
	JMP    l2_scalar_loop

l2_done:
	MOVSS X0, ret+48(FP)
	RET

// func L2Distance4AVX2(q []float32, b0 []float32, b1 []float32, b2 []float32, b3 []float32) (d0 float32, d1 float32, d2 float32, d3 float32)
// Requires: AVX, FMA3, SSE
TEXT ·L2Distance4AVX2(SB), NOSPLIT, $0-136
	MOVQ   q_base+0(FP), AX
	MOVQ   b0_base+24(FP), CX
	MOVQ   b1_base+48(FP), DX
	MOVQ   b2_base+72(FP), BX
	MOVQ   b3_base+96(FP), SI
	MOVQ   q_len+8(FP), DI
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3

l2x4_loop:
	CMPQ        DI, $0x08
	JL          l2x4_tail
	VMOVUPS     (AX), Y4
	VMOVUPS     (CX), Y5
	VSUBPS      Y4, Y5, Y5
	VFMADD231PS Y5, Y5, Y0
	VMOVUPS     (DX), Y5
	VSUBPS      Y4, Y5, Y5
	VFMADD231PS Y5, Y5, Y1
	VMOVUPS     (BX), Y5
	VSUBPS      Y4, Y5, Y5
	VFMADD231PS Y5, Y5, Y2
	VMOVUPS     (SI), Y5
	VSUBPS      Y4, Y5, Y5
	VFMADD231PS Y5, Y5, Y3
	ADDQ        $0x20, AX
	ADDQ        $0x20, CX
	ADDQ        $0x20, DX
	ADDQ        $0x20, BX
	ADDQ        $0x20, SI
	SUBQ        $0x08, DI
	JMP         l2x4_loop

l2x4_tail:
	VEXTRACTF128 $0x01, Y0, X4
	VADDPS       X4, X0, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0
	VEXTRACTF128 $0x01, Y1, X4
	VADDPS       X4, X1, X1
	VHADDPS      X1, X1, X1
	VHADDPS      X1, X1, X1
	VEXTRACTF128 $0x01, Y2, X4
	VADDPS       X4, X2, X2
	VHADDPS      X2, X2, X2
	VHADDPS      X2, X2, X2
	VEXTRACTF128 $0x01, Y3, X4
	VADDPS       X4, X3, X3
	VHADDPS      X3, X3, X3
	VHADDPS      X3, X3, X3

l2x4_scalar_loop:
	CMPQ   DI, $0x00
	JE     l2x4_done
	VMOVSS (AX), X4
	VMOVSS (CX), X5
	VSUBSS X4, X5, X5
	VMULSS X5, X5, X5
	VADDSS X5, X0, X0
	VMOVSS (DX), X5
	VSUBSS X4, X5, X5
	VMULSS X5, X5, X5
	VADDSS X5, X1, X1
	VMOVSS (BX), X5
	VSUBSS X4, X5, X5
	VMULSS X5, X5, X5
	VADDSS X5, X2, X2
	VMOVSS (SI), X5
	VSUBSS X4, X5, X5
	VMULSS X5, X5, X5
	VADDSS X5, X3, X3
	ADDQ   $0x04, AX
	ADDQ   $0x04, CX
	ADDQ   $0x04, DX
	ADDQ   $0x04, BX
	ADDQ   $0x04, SI
	SUBQ   $0x01, DI
	JMP    l2x4_scalar_loop

l2x4_done:
	MOVSS X0, d0+120(FP)
	MOVSS X1, d1+124(FP)
	MOVSS X2, d2+128(FP)
	MOVSS X3, d3+132(FP)
	RET
