// Code generated by command: go run generate.go -out distance_amd64.s -stubs stub_amd64.go. DO NOT EDIT.

package simd

// DotProductAVX2 computes the dot product of two float32 slices using AVX2, unrolled.
func DotProductAVX2(a []float32, b []float32) float32

// L2DistanceAVX2 computes the L2 distance of two float32 slices using AVX2, unrolled.
func L2DistanceAVX2(a []float32, b []float32) float32

// L2Distance4AVX2 computes four L2 distances against one query using AVX2.
func L2Distance4AVX2(q []float32, b0 []float32, b1 []float32, b2 []float32, b3 []float32) (d0 float32, d1 float32, d2 float32, d3 float32)
