// Code generated by command: go run generate.go -out distance_amd64.s -stubs stub_amd64.go. DO NOT EDIT.

package simd

// DotProductAVX2 computes the dot product of two float32 slices using AVX2, unrolled.
//
//go:noescape
func DotProductAVX2(a []float32, b []float32) float32

// L2DistanceAVX2 computes the L2 distance of two float32 slices using AVX2, unrolled.
//
//go:noescape
func L2DistanceAVX2(a []float32, b []float32) float32

// L2Distance4AVX2 computes four L2 distances against one query using AVX2.
//
//go:noescape
func L2Distance4AVX2(q []float32, b0 []float32, b1 []float32, b2 []float32, b3 []float32) (d0 float32, d1 float32, d2 float32, d3 float32)

// l2Distance4PtrAVX2 computes four squared L2 distances in one query pass using AVX2.
//
//go:noescape
func l2Distance4PtrAVX2(q []float32, b0 *byte, b1 *byte, b2 *byte, b3 *byte) (d0 float32, d1 float32, d2 float32, d3 float32)

// l2Distance8PtrAVX2 computes eight squared L2 distances in one query pass using AVX2.
//
//go:noescape
func l2Distance8PtrAVX2(q []float32, b0 *byte, b1 *byte, b2 *byte, b3 *byte, b4 *byte, b5 *byte, b6 *byte, b7 *byte) (d0 float32, d1 float32, d2 float32, d3 float32, d4 float32, d5 float32, d6 float32, d7 float32)

// l2AnyLessThan8PtrAVX2 reports whether any squared L2 distance is below cutoff using AVX2.
//
//go:noescape
func l2AnyLessThan8PtrAVX2(q []float32, b0 *byte, b1 *byte, b2 *byte, b3 *byte, b4 *byte, b5 *byte, b6 *byte, b7 *byte, cutoff float32) uint32

//go:noescape
func prefetch8L1AMD64(ptrs *[8]*byte)
