# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_OpenDB <- function(path) {
    .Call(`_libravdb_r_OpenDB`, path)
}

r_CloseDB <- function(dbID) {
    invisible(.Call(`_libravdb_r_CloseDB`, dbID))
}

r_Ping <- function(dbID) {
    invisible(.Call(`_libravdb_r_Ping`, dbID))
}

r_SetGlobalMemoryLimit <- function(dbID, limit) {
    invisible(.Call(`_libravdb_r_SetGlobalMemoryLimit`, dbID, limit))
}

r_Vacuum <- function(dbID) {
    invisible(.Call(`_libravdb_r_Vacuum`, dbID))
}

r_DropDatabase <- function(dbID) {
    invisible(.Call(`_libravdb_r_DropDatabase`, dbID))
}

r_ListCollections <- function(dbID) {
    .Call(`_libravdb_r_ListCollections`, dbID)
}

r_CreateCollection <- function(dbID, name, dim) {
    .Call(`_libravdb_r_CreateCollection`, dbID, name, dim)
}

r_GetCollection <- function(dbID, name) {
    .Call(`_libravdb_r_GetCollection`, dbID, name)
}

r_GetCollectionCount <- function(colID) {
    .Call(`_libravdb_r_GetCollectionCount`, colID)
}

r_InsertVector <- function(colID, id, vector, dim, metadataJSON) {
    invisible(.Call(`_libravdb_r_InsertVector`, colID, id, vector, dim, metadataJSON))
}

r_UpdateVector <- function(colID, id, vector, dim, metadataJSON) {
    invisible(.Call(`_libravdb_r_UpdateVector`, colID, id, vector, dim, metadataJSON))
}

r_UpdateVectorIfVersion <- function(colID, id, vector, dim, metadataJSON, expectedVersion) {
    invisible(.Call(`_libravdb_r_UpdateVectorIfVersion`, colID, id, vector, dim, metadataJSON, expectedVersion))
}

r_DeleteVector <- function(colID, id) {
    invisible(.Call(`_libravdb_r_DeleteVector`, colID, id))
}

r_GetVector <- function(colID, id) {
    .Call(`_libravdb_r_GetVector`, colID, id)
}

r_QueryVector <- function(colID, vector, dim, limit, filterJSON) {
    .Call(`_libravdb_r_QueryVector`, colID, vector, dim, limit, filterJSON)
}

r_ScanCollection <- function(colID, offset, limit) {
    .Call(`_libravdb_r_ScanCollection`, colID, offset, limit)
}

r_DatabaseQuery <- function(dbID, sql) {
    .Call(`_libravdb_r_DatabaseQuery`, dbID, sql)
}

r_DatabaseQueryWithParams <- function(dbID, sql, paramsStr) {
    .Call(`_libravdb_r_DatabaseQueryWithParams`, dbID, sql, paramsStr)
}

r_DatabaseLatestCommitLSN <- function(dbID) {
    .Call(`_libravdb_r_DatabaseLatestCommitLSN`, dbID)
}
