package pgwire

import (
	"context"
	"crypto/hmac"
	cryptorand "crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/binary"
	"fmt"
	"io"
	"strconv"
	"strings"
	"unicode/utf8"

	"golang.org/x/text/secure/precis"
)

const (
	// DefaultSCRAMIterations is the PostgreSQL-compatible minimum iteration
	// count for SCRAM-SHA-256 credentials generated by this package.
	DefaultSCRAMIterations   = 4096
	maxSCRAMIterations       = 10_000_000
	maxSCRAMMessageBytes     = 64 * 1024
	maxSCRAMSaltBytes        = 1024
	maxSCRAMUsernameBytes    = 256
	maxSCRAMNonceBytes       = 256
	scramSHA256Mechanism     = "SCRAM-SHA-256"
	scramSHA256PlusMechanism = "SCRAM-SHA-256-PLUS"
	scramTLSBindingType      = "tls-server-end-point"
)

// SCRAMCredential is a salted SCRAM-SHA-256 verifier. It deliberately stores
// no plaintext password and is safe to persist in an application credential
// store. The byte slices are cloned when accepted by NewServer.
type SCRAMCredential struct {
	Username   string
	Salt       []byte
	Iterations int
	StoredKey  []byte
	ServerKey  []byte
}

// NewSCRAMCredential derives a SCRAM verifier from a password. Password bytes
// are used only during derivation and are not retained in the result.
func NewSCRAMCredential(username, password string) (SCRAMCredential, error) {
	return newSCRAMCredentialWithIterations(username, password, DefaultSCRAMIterations)
}

// NewSCRAMCredentialWithIterations is useful when a deployment chooses a
// stronger work factor than the default. Iterations below the PostgreSQL
// compatible minimum or above the DoS protection ceiling are rejected.
func NewSCRAMCredentialWithIterations(username, password string, iterations int) (SCRAMCredential, error) {
	return newSCRAMCredentialWithIterations(username, password, iterations)
}

func newSCRAMCredentialWithIterations(username, password string, iterations int) (SCRAMCredential, error) {
	if username == "" {
		return SCRAMCredential{}, fmt.Errorf("SCRAM username must not be empty")
	}
	if iterations < DefaultSCRAMIterations || iterations > maxSCRAMIterations {
		return SCRAMCredential{}, fmt.Errorf("SCRAM iterations must be between %d and %d", DefaultSCRAMIterations, maxSCRAMIterations)
	}
	salt := make([]byte, 16)
	if _, err := io.ReadFull(cryptorand.Reader, salt); err != nil {
		return SCRAMCredential{}, fmt.Errorf("generate SCRAM salt: %w", err)
	}
	return deriveSCRAMCredential(username, password, salt, iterations)
}

func deriveSCRAMCredential(username, password string, salt []byte, iterations int) (SCRAMCredential, error) {
	if err := validateSCRAMUsername(username); err != nil {
		return SCRAMCredential{}, err
	}
	if err := validateSCRAMIterations(iterations); err != nil {
		return SCRAMCredential{}, err
	}
	if len(salt) < 8 || len(salt) > maxSCRAMSaltBytes {
		return SCRAMCredential{}, fmt.Errorf("SCRAM salt must contain between 8 and %d bytes", maxSCRAMSaltBytes)
	}
	preparedPassword, err := normalizeSCRAMPassword(password)
	if err != nil {
		return SCRAMCredential{}, err
	}
	salted := scramHi(preparedPassword, salt, iterations)
	clientKey := scramHMAC(salted, []byte("Client Key"))
	stored := sha256.Sum256(clientKey)
	server := scramHMAC(salted, []byte("Server Key"))
	return SCRAMCredential{
		Username:   username,
		Salt:       append([]byte(nil), salt...),
		Iterations: iterations,
		StoredKey:  append([]byte(nil), stored[:]...),
		ServerKey:  append([]byte(nil), server...),
	}, nil
}

func normalizeSCRAMPassword(password string) ([]byte, error) {
	// PRECIS OpaqueString is the RFC 7613 successor used by PostgreSQL clients
	// for SASLprep-compatible password preparation. Credential creation is
	// deliberately strict: accepting a raw fallback after preparation fails
	// would make equivalent-looking passwords authenticate differently across
	// clients and would reintroduce the legacy fail-open behavior.
	if !utf8.ValidString(password) {
		return nil, fmt.Errorf("SCRAM password is not valid UTF-8")
	}
	prepared, err := precis.OpaqueString.Bytes([]byte(password))
	if err != nil {
		return nil, fmt.Errorf("SCRAM password fails PRECIS OpaqueString preparation: %w", err)
	}
	return prepared, nil
}

func cloneSCRAMCredential(c SCRAMCredential) SCRAMCredential {
	c.Salt = append([]byte(nil), c.Salt...)
	c.StoredKey = append([]byte(nil), c.StoredKey...)
	c.ServerKey = append([]byte(nil), c.ServerKey...)
	return c
}

func cloneSCRAMCredentials(in map[string]SCRAMCredential) map[string]SCRAMCredential {
	if in == nil {
		return nil
	}
	out := make(map[string]SCRAMCredential, len(in))
	for name, credential := range in {
		out[name] = cloneSCRAMCredential(credential)
	}
	return out
}

func validateSCRAMConfig(config ServerConfig) error {
	if !scramAuthEnabled(config) {
		if config.RequireChannelBinding {
			return fmt.Errorf("RequireChannelBinding requires SCRAM authentication")
		}
		return nil
	}
	if !config.RequireTLS {
		return fmt.Errorf("SCRAM authentication requires RequireTLS to protect the session")
	}
	if len(config.Credentials) == 0 && config.PasswordLookup == nil && config.PasswordLookupContext == nil {
		return fmt.Errorf("SCRAM authentication requires Credentials, PasswordLookup, or PasswordLookupContext")
	}
	for username, credential := range config.Credentials {
		if username == "" {
			return fmt.Errorf("SCRAM credential map contains an empty username")
		}
		if credential.Username != username {
			return fmt.Errorf("SCRAM credential username %q does not match map key", credential.Username)
		}
		if err := validateSCRAMCredential(credential); err != nil {
			return fmt.Errorf("invalid SCRAM credential %q: %w", username, err)
		}
	}
	return nil
}

func ensureSCRAMUnknownCredential(config *ServerConfig) error {
	if config == nil || !scramAuthEnabled(*config) || config.scramUnknownCredential != nil {
		return nil
	}
	credential, err := newSCRAMCredentialWithIterations("__libra_unknown__", "invalid-user", DefaultSCRAMIterations)
	if err != nil {
		return fmt.Errorf("generate SCRAM unknown-user verifier: %w", err)
	}
	config.scramUnknownCredential = &credential
	return nil
}

func scramAuthEnabled(config ServerConfig) bool {
	return config.RequireAuthentication || len(config.Credentials) > 0 || config.PasswordLookup != nil || config.PasswordLookupContext != nil
}

func validateSCRAMCredential(credential SCRAMCredential) error {
	if err := validateSCRAMUsername(credential.Username); err != nil {
		return err
	}
	if len(credential.Salt) < 8 || len(credential.Salt) > maxSCRAMSaltBytes {
		return fmt.Errorf("salt length is outside the permitted range")
	}
	if err := validateSCRAMIterations(credential.Iterations); err != nil {
		return err
	}
	if len(credential.StoredKey) != sha256.Size || len(credential.ServerKey) != sha256.Size {
		return fmt.Errorf("stored/server key must be SHA-256 sized")
	}
	return nil
}

func validateSCRAMUsername(username string) error {
	if username == "" {
		return fmt.Errorf("SCRAM username must not be empty")
	}
	if len(username) > maxSCRAMUsernameBytes {
		return fmt.Errorf("SCRAM username is too long")
	}
	if !utf8.ValidString(username) {
		return fmt.Errorf("SCRAM username is not valid UTF-8")
	}
	for i := 0; i < len(username); i++ {
		if username[i] < 0x20 || username[i] == 0x7f {
			return fmt.Errorf("SCRAM username contains a control character")
		}
	}
	return nil
}

func validateSCRAMIterations(iterations int) error {
	if iterations < DefaultSCRAMIterations || iterations > maxSCRAMIterations {
		return fmt.Errorf("SCRAM iterations must be between %d and %d", DefaultSCRAMIterations, maxSCRAMIterations)
	}
	return nil
}

func authenticateSCRAM(rw io.ReadWriter, startupUser string, config ServerConfig) error {
	return authenticateSCRAMContext(context.Background(), rw, startupUser, config)
}

func authenticateSCRAMContext(ctx context.Context, rw io.ReadWriter, startupUser string, config ServerConfig) error {
	if ctx == nil {
		ctx = context.Background()
	}
	if err := ensureSCRAMUnknownCredential(&config); err != nil {
		return err
	}
	if config.RequireChannelBinding && !config.scramChannelBindingOK {
		return fmt.Errorf("SCRAM channel binding requires a TLS server certificate")
	}
	if err := sendAuthSASL(rw, config.scramChannelBindingOK); err != nil {
		return err
	}
	msgType, payload, err := readMessageWithMax(rw, maxSCRAMMessageBytes)
	if err != nil {
		return fmt.Errorf("read SCRAM initial response: %w", err)
	}
	if msgType != msgPassword {
		return fmt.Errorf("SCRAM expected PasswordMessage, got %q", msgType)
	}
	if len(payload) > maxSCRAMMessageBytes {
		return fmt.Errorf("SCRAM initial response exceeds size limit")
	}
	mechanism, initial, err := parseSASLInitialResponse(payload)
	if err != nil || (mechanism != scramSHA256Mechanism && mechanism != scramSHA256PlusMechanism) {
		return fmt.Errorf("invalid SCRAM mechanism")
	}
	if mechanism == scramSHA256PlusMechanism && !config.scramChannelBindingOK {
		return fmt.Errorf("SCRAM-SHA-256-PLUS requires TLS channel binding")
	}
	if config.RequireChannelBinding && mechanism != scramSHA256PlusMechanism {
		return fmt.Errorf("SCRAM channel binding is required")
	}
	if len(initial) == 0 || len(initial) > maxSCRAMMessageBytes {
		return fmt.Errorf("SCRAM client-first message exceeds size limit")
	}
	clientFirst, err := parseSCRAMClientFirstForMechanism(initial, mechanism)
	if err != nil {
		return fmt.Errorf("invalid SCRAM client-first message: %w", err)
	}
	decodedUsername, err := scramUnescape(clientFirst.username)
	if err != nil {
		return fmt.Errorf("invalid SCRAM username: %w", err)
	}
	if err := validateSCRAMUsername(decodedUsername); err != nil {
		return fmt.Errorf("invalid SCRAM username: %w", err)
	}
	if startupUser != "" && decodedUsername != startupUser {
		return fmt.Errorf("SCRAM username does not match startup user")
	}

	lookupUser := startupUser
	if lookupUser == "" {
		lookupUser = decodedUsername
	}
	credential, found, lookupErr := lookupSCRAMCredentialContext(ctx, config, lookupUser)
	if lookupErr != nil {
		return lookupErr
	}
	if !found {
		// Continue the full exchange with one precomputed verifier. Reusing the
		// mock verifier avoids attacker-triggered PBKDF2 work on every unknown
		// username. The salt is still randomized per exchange so a stable fake
		// salt cannot become an account-existence oracle.
		if config.scramUnknownCredential == nil {
			return fmt.Errorf("SCRAM unknown-user verifier is unavailable")
		}
		credential, err = unknownSCRAMCredentialForExchange(*config.scramUnknownCredential)
		if err != nil {
			return err
		}
	} else if credential.Username != lookupUser {
		return fmt.Errorf("SCRAM credential username does not match requested user")
	}
	if err := validateSCRAMCredential(credential); err != nil {
		return err
	}

	serverNonceBytes := make([]byte, 18)
	if _, err := io.ReadFull(cryptorand.Reader, serverNonceBytes); err != nil {
		return fmt.Errorf("generate SCRAM nonce: %w", err)
	}
	serverNonce := clientFirst.nonce + base64.RawStdEncoding.EncodeToString(serverNonceBytes)
	serverFirst := "r=" + serverNonce + ",s=" + base64.StdEncoding.EncodeToString(credential.Salt) + ",i=" + strconv.Itoa(credential.Iterations)
	if err := sendAuthSASLContinue(rw, serverFirst); err != nil {
		return err
	}

	msgType, payload, err = readMessageWithMax(rw, maxSCRAMMessageBytes)
	if err != nil {
		return fmt.Errorf("read SCRAM client-final response: %w", err)
	}
	if msgType != msgPassword {
		return fmt.Errorf("SCRAM expected PasswordMessage for client-final, got %q", msgType)
	}
	if len(payload) == 0 || len(payload) > maxSCRAMMessageBytes {
		return fmt.Errorf("SCRAM client-final message exceeds size limit")
	}
	clientFinal, err := parseSCRAMClientFinal(string(payload))
	if err != nil {
		return fmt.Errorf("invalid SCRAM client-final message: %w", err)
	}
	expectedChannelBinding, err := scramExpectedChannelBinding(mechanism, config.scramChannelBinding)
	if err != nil {
		return err
	}
	providedChannelBinding, err := base64.StdEncoding.DecodeString(clientFinal.channelBinding)
	if err != nil || subtle.ConstantTimeCompare(providedChannelBinding, expectedChannelBinding) != 1 || subtle.ConstantTimeCompare([]byte(clientFinal.nonce), []byte(serverNonce)) != 1 {
		return fmt.Errorf("SCRAM channel binding or nonce mismatch")
	}
	proof, err := base64.StdEncoding.DecodeString(clientFinal.proof)
	if err != nil || len(proof) != sha256.Size {
		return fmt.Errorf("invalid SCRAM proof")
	}
	authMessage := clientFirst.bare + "," + serverFirst + "," + clientFinal.withoutProof
	if !verifySCRAMProof(credential.StoredKey, []byte(authMessage), proof) {
		return fmt.Errorf("SCRAM authentication failed")
	}
	serverSignature := scramHMAC(credential.ServerKey, []byte(authMessage))
	if err := sendAuthSASLFinal(rw, base64.StdEncoding.EncodeToString(serverSignature)); err != nil {
		return err
	}
	return sendAuthOK(rw)
}

func unknownSCRAMCredentialForExchange(base SCRAMCredential) (SCRAMCredential, error) {
	credential := cloneSCRAMCredential(base)
	credential.Salt = make([]byte, 16)
	if _, err := io.ReadFull(cryptorand.Reader, credential.Salt); err != nil {
		return SCRAMCredential{}, fmt.Errorf("generate SCRAM unknown-user salt: %w", err)
	}
	return credential, nil
}

func verifySCRAMProof(storedKey, authMessage, proof []byte) bool {
	if len(storedKey) != sha256.Size || len(proof) != sha256.Size {
		return false
	}
	clientSignature := scramHMAC(storedKey, authMessage)
	recoveredClientKey := make([]byte, len(proof))
	for i := range proof {
		recoveredClientKey[i] = proof[i] ^ clientSignature[i]
	}
	recoveredStored := sha256.Sum256(recoveredClientKey)
	return hmac.Equal(recoveredStored[:], storedKey)
}

func lookupSCRAMCredential(config ServerConfig, username string) (SCRAMCredential, bool) {
	credential, found, _ := lookupSCRAMCredentialContext(context.Background(), config, username)
	return credential, found
}

func lookupSCRAMCredentialContext(ctx context.Context, config ServerConfig, username string) (SCRAMCredential, bool, error) {
	if ctx == nil {
		ctx = context.Background()
	}
	if config.PasswordLookupContext != nil {
		lookupCtx := ctx
		cancel := func() {}
		timeout := config.PasswordLookupTimeout
		if timeout == 0 {
			timeout = DefaultPasswordLookupTimeout
		}
		if timeout > 0 {
			lookupCtx, cancel = context.WithTimeout(ctx, timeout)
		}
		credential, ok := config.PasswordLookupContext(lookupCtx, username)
		lookupErr := lookupCtx.Err()
		cancel()
		if lookupErr != nil {
			return SCRAMCredential{}, false, fmt.Errorf("SCRAM credential lookup: %w", lookupErr)
		}
		if ok {
			credential = cloneSCRAMCredential(credential)
			if credential.Username != username {
				return SCRAMCredential{}, false, nil
			}
			return credential, true, nil
		}
	}
	if config.PasswordLookup != nil {
		if credential, ok := config.PasswordLookup(username); ok {
			credential = cloneSCRAMCredential(credential)
			if credential.Username != username {
				return SCRAMCredential{}, false, nil
			}
			return credential, true, nil
		}
	}
	credential, ok := config.Credentials[username]
	if !ok {
		return SCRAMCredential{}, false, nil
	}
	credential = cloneSCRAMCredential(credential)
	if credential.Username != username {
		return SCRAMCredential{}, false, nil
	}
	return credential, true, nil
}

func sendAuthSASL(w io.Writer, offerPlus bool) error {
	payload := make([]byte, 4)
	binary.BigEndian.PutUint32(payload, 10)
	if offerPlus {
		payload = append(payload, []byte(scramSHA256PlusMechanism)...)
		payload = append(payload, 0)
	}
	payload = append(payload, []byte(scramSHA256Mechanism)...)
	payload = append(payload, 0, 0)
	return WriteMessage(w, msgAuth, payload)
}

func sendAuthSASLContinue(w io.Writer, message string) error {
	payload := make([]byte, 4)
	binary.BigEndian.PutUint32(payload, 11)
	payload = append(payload, message...)
	return WriteMessage(w, msgAuth, payload)
}

func sendAuthSASLFinal(w io.Writer, verifier string) error {
	payload := make([]byte, 4)
	binary.BigEndian.PutUint32(payload, 12)
	payload = append(payload, "v="...)
	payload = append(payload, verifier...)
	return WriteMessage(w, msgAuth, payload)
}

func parseSASLInitialResponse(payload []byte) (string, string, error) {
	if len(payload) > maxSCRAMMessageBytes {
		return "", "", fmt.Errorf("SASL initial response exceeds size limit")
	}
	zero := indexByte(payload, 0)
	if zero < 0 || zero+5 > len(payload) {
		return "", "", fmt.Errorf("truncated SASL initial response")
	}
	length := int32(binary.BigEndian.Uint32(payload[zero+1 : zero+5]))
	if length < 0 || int64(zero)+5+int64(length) != int64(len(payload)) {
		return "", "", fmt.Errorf("invalid SASL initial response length")
	}
	mechanism := string(payload[:zero])
	if !validSASLMechanism(mechanism) {
		return "", "", fmt.Errorf("invalid SASL mechanism name")
	}
	return mechanism, string(payload[zero+5:]), nil
}

func validSASLMechanism(mechanism string) bool {
	if mechanism == "" || len(mechanism) > 256 {
		return false
	}
	for i := 0; i < len(mechanism); i++ {
		c := mechanism[i]
		if !((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-') {
			return false
		}
	}
	return true
}

type scramClientFirst struct {
	bare      string
	gs2Header string
	username  string
	nonce     string
}

func parseSCRAMClientFirst(message string) (scramClientFirst, error) {
	return parseSCRAMClientFirstForMechanism(message, scramSHA256Mechanism)
}

func parseSCRAMClientFirstForMechanism(message, mechanism string) (scramClientFirst, error) {
	if len(message) > maxSCRAMMessageBytes || !utf8.ValidString(message) {
		return scramClientFirst{}, fmt.Errorf("client-first message is invalid or too large")
	}
	gs2Header := "n,,"
	if mechanism == scramSHA256PlusMechanism {
		gs2Header = "p=" + scramTLSBindingType + ",,"
	} else if mechanism != scramSHA256Mechanism {
		return scramClientFirst{}, fmt.Errorf("unsupported SCRAM mechanism")
	}
	if !strings.HasPrefix(message, gs2Header) {
		return scramClientFirst{}, fmt.Errorf("unsupported GS2 header")
	}
	bare := message[len(gs2Header):]
	attrs, err := parseSCRAMAttributes(bare)
	if err != nil {
		return scramClientFirst{}, err
	}
	username, okUser := attrs['n']
	nonce, okNonce := attrs['r']
	if !okUser || !okNonce || username == "" || nonce == "" || len(username) > maxSCRAMUsernameBytes*2 {
		return scramClientFirst{}, fmt.Errorf("client-first requires username and nonce")
	}
	if _, mandatoryExtension := attrs['m']; mandatoryExtension {
		return scramClientFirst{}, fmt.Errorf("unsupported mandatory SCRAM extension")
	}
	if err := validateSCRAMNonce(nonce); err != nil {
		return scramClientFirst{}, err
	}
	return scramClientFirst{bare: bare, gs2Header: gs2Header, username: username, nonce: nonce}, nil
}

func scramExpectedChannelBinding(mechanism string, binding []byte) ([]byte, error) {
	switch mechanism {
	case scramSHA256Mechanism:
		return []byte("n,,"), nil
	case scramSHA256PlusMechanism:
		if len(binding) == 0 {
			return nil, fmt.Errorf("SCRAM-SHA-256-PLUS channel binding data is unavailable")
		}
		out := make([]byte, 0, len(scramTLSBindingType)+len(binding)+5)
		out = append(out, "p="+scramTLSBindingType+",,"...)
		out = append(out, binding...)
		return out, nil
	default:
		return nil, fmt.Errorf("unsupported SCRAM mechanism")
	}
}

type scramClientFinal struct {
	withoutProof   string
	channelBinding string
	nonce          string
	proof          string
}

func parseSCRAMClientFinal(message string) (scramClientFinal, error) {
	if len(message) > maxSCRAMMessageBytes || !utf8.ValidString(message) {
		return scramClientFinal{}, fmt.Errorf("client-final message is invalid or too large")
	}
	proofIndex := strings.LastIndex(message, ",p=")
	if proofIndex <= 0 {
		return scramClientFinal{}, fmt.Errorf("client-final proof missing")
	}
	withoutProof := message[:proofIndex]
	attrs, err := parseSCRAMAttributes(message)
	if err != nil {
		return scramClientFinal{}, err
	}
	channelBinding, okC := attrs['c']
	nonce, okNonce := attrs['r']
	proof, okProof := attrs['p']
	if !okC || !okNonce || !okProof || proof == "" {
		return scramClientFinal{}, fmt.Errorf("client-final requires channel binding, nonce, and proof")
	}
	if err := validateSCRAMNonce(nonce); err != nil {
		return scramClientFinal{}, err
	}
	return scramClientFinal{withoutProof: withoutProof, channelBinding: channelBinding, nonce: nonce, proof: proof}, nil
}

func parseSCRAMAttributes(message string) (map[byte]string, error) {
	if message == "" || len(message) > maxSCRAMMessageBytes || !utf8.ValidString(message) {
		return nil, fmt.Errorf("invalid SCRAM attribute message")
	}
	attrs := make(map[byte]string, 4)
	for _, field := range strings.Split(message, ",") {
		if len(field) < 3 || field[1] != '=' {
			return nil, fmt.Errorf("malformed SCRAM attribute")
		}
		key := field[0]
		if !((key >= 'A' && key <= 'Z') || (key >= 'a' && key <= 'z')) {
			return nil, fmt.Errorf("invalid SCRAM attribute name")
		}
		if _, exists := attrs[key]; exists {
			return nil, fmt.Errorf("duplicate SCRAM attribute %q", key)
		}
		value := field[2:]
		if value == "" {
			return nil, fmt.Errorf("empty SCRAM attribute %q", key)
		}
		for i := 0; i < len(value); i++ {
			if value[i] < 0x20 || value[i] == 0x7f {
				return nil, fmt.Errorf("SCRAM attribute %q contains a control character", key)
			}
		}
		attrs[key] = value
	}
	return attrs, nil
}

func validateSCRAMNonce(nonce string) error {
	if nonce == "" || len(nonce) > maxSCRAMNonceBytes {
		return fmt.Errorf("invalid SCRAM nonce")
	}
	for i := 0; i < len(nonce); i++ {
		c := nonce[i]
		if c == ',' || c < 0x21 || c > 0x7e {
			return fmt.Errorf("invalid SCRAM nonce")
		}
	}
	return nil
}

func scramHi(password, salt []byte, iterations int) []byte {
	var input []byte
	input = append(input, salt...)
	input = append(input, 0, 0, 0, 1)
	u := scramHMAC(password, input)
	t := append([]byte(nil), u...)
	for i := 1; i < iterations; i++ {
		u = scramHMAC(password, u)
		for j := range t {
			t[j] ^= u[j]
		}
	}
	return t
}

func scramHMAC(key, data []byte) []byte {
	h := hmac.New(sha256.New, key)
	_, _ = h.Write(data)
	return h.Sum(nil)
}

func scramUnescape(username string) (string, error) {
	if username == "" {
		return "", fmt.Errorf("username is empty")
	}
	if len(username) > maxSCRAMUsernameBytes*2 {
		return "", fmt.Errorf("username is too long")
	}
	var out strings.Builder
	out.Grow(len(username))
	for i := 0; i < len(username); i++ {
		if username[i] != '=' {
			if username[i] == ',' || username[i] < 0x20 || username[i] == 0x7f {
				return "", fmt.Errorf("username contains an invalid character")
			}
			out.WriteByte(username[i])
			continue
		}
		if i+2 >= len(username) {
			return "", fmt.Errorf("truncated username escape")
		}
		switch username[i+1 : i+3] {
		case "2C":
			out.WriteByte(',')
		case "3D":
			out.WriteByte('=')
		default:
			return "", fmt.Errorf("invalid username escape")
		}
		i += 2
	}
	return out.String(), nil
}

func indexByte(value []byte, target byte) int {
	for i, c := range value {
		if c == target {
			return i
		}
	}
	return -1
}
