package libravdb

import (
	"context"
	"testing"
)

func TestSQLDjangoMigrationRecorderDDL(t *testing.T) {
	db, err := Open(WithStoragePath(":memory:django_ddl_test"), WithMetrics(false))
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer db.Close()

	ctx := context.Background()
	_, err = db.Query(ctx, `CREATE TABLE "django_migrations" (
		"id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
		"app" varchar(255) NOT NULL,
		"name" varchar(255) NOT NULL,
		"applied" timestamp with time zone NOT NULL
	)`)
	if err != nil {
		t.Fatalf("CREATE TABLE: %v", err)
	}

	collection, err := db.GetCollection("django_migrations")
	if err != nil {
		t.Fatalf("GetCollection: %v", err)
	}
	config := collection.Config()
	for _, column := range []string{"app", "name", "applied"} {
		if _, ok := config.MetadataSchema[column]; !ok {
			t.Fatalf("metadata schema missing %q: %#v", column, config.MetadataSchema)
		}
	}
	if _, err := db.Query(ctx, `INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('django_pgwire_probe', '0001_initial', '2026-01-01T00:00:00Z')`); err != nil {
		t.Fatalf("INSERT: %v", err)
	}
	rows, err := db.Query(ctx, `SELECT id, app, name FROM "django_migrations"`)
	if err != nil || len(rows.Results) != 1 {
		t.Fatalf("identity row: results=%#v err=%v", rows, err)
	}
}
