// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// r_OpenDB
int r_OpenDB(std::string path);
RcppExport SEXP _libravdb_r_OpenDB(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(r_OpenDB(path));
    return rcpp_result_gen;
END_RCPP
}
// r_CloseDB
void r_CloseDB(int dbID);
RcppExport SEXP _libravdb_r_CloseDB(SEXP dbIDSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type dbID(dbIDSEXP);
    r_CloseDB(dbID);
    return R_NilValue;
END_RCPP
}
// r_Ping
void r_Ping(int dbID);
RcppExport SEXP _libravdb_r_Ping(SEXP dbIDSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type dbID(dbIDSEXP);
    r_Ping(dbID);
    return R_NilValue;
END_RCPP
}
// r_SetGlobalMemoryLimit
void r_SetGlobalMemoryLimit(int dbID, double limit);
RcppExport SEXP _libravdb_r_SetGlobalMemoryLimit(SEXP dbIDSEXP, SEXP limitSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type dbID(dbIDSEXP);
    Rcpp::traits::input_parameter< double >::type limit(limitSEXP);
    r_SetGlobalMemoryLimit(dbID, limit);
    return R_NilValue;
END_RCPP
}
// r_Vacuum
void r_Vacuum(int dbID);
RcppExport SEXP _libravdb_r_Vacuum(SEXP dbIDSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type dbID(dbIDSEXP);
    r_Vacuum(dbID);
    return R_NilValue;
END_RCPP
}
// r_DropDatabase
void r_DropDatabase(int dbID);
RcppExport SEXP _libravdb_r_DropDatabase(SEXP dbIDSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type dbID(dbIDSEXP);
    r_DropDatabase(dbID);
    return R_NilValue;
END_RCPP
}
// r_ListCollections
String r_ListCollections(int dbID);
RcppExport SEXP _libravdb_r_ListCollections(SEXP dbIDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type dbID(dbIDSEXP);
    rcpp_result_gen = Rcpp::wrap(r_ListCollections(dbID));
    return rcpp_result_gen;
END_RCPP
}
// r_CreateCollection
int r_CreateCollection(int dbID, std::string name, int dim);
RcppExport SEXP _libravdb_r_CreateCollection(SEXP dbIDSEXP, SEXP nameSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type dbID(dbIDSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(r_CreateCollection(dbID, name, dim));
    return rcpp_result_gen;
END_RCPP
}
// r_GetCollection
int r_GetCollection(int dbID, std::string name);
RcppExport SEXP _libravdb_r_GetCollection(SEXP dbIDSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type dbID(dbIDSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(r_GetCollection(dbID, name));
    return rcpp_result_gen;
END_RCPP
}
// r_GetCollectionCount
double r_GetCollectionCount(int colID);
RcppExport SEXP _libravdb_r_GetCollectionCount(SEXP colIDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type colID(colIDSEXP);
    rcpp_result_gen = Rcpp::wrap(r_GetCollectionCount(colID));
    return rcpp_result_gen;
END_RCPP
}
// r_InsertVector
void r_InsertVector(int colID, std::string id, NumericVector vector, int dim, std::string metadataJSON);
RcppExport SEXP _libravdb_r_InsertVector(SEXP colIDSEXP, SEXP idSEXP, SEXP vectorSEXP, SEXP dimSEXP, SEXP metadataJSONSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type colID(colIDSEXP);
    Rcpp::traits::input_parameter< std::string >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vector(vectorSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< std::string >::type metadataJSON(metadataJSONSEXP);
    r_InsertVector(colID, id, vector, dim, metadataJSON);
    return R_NilValue;
END_RCPP
}
// r_UpdateVector
void r_UpdateVector(int colID, std::string id, NumericVector vector, int dim, std::string metadataJSON);
RcppExport SEXP _libravdb_r_UpdateVector(SEXP colIDSEXP, SEXP idSEXP, SEXP vectorSEXP, SEXP dimSEXP, SEXP metadataJSONSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type colID(colIDSEXP);
    Rcpp::traits::input_parameter< std::string >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vector(vectorSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< std::string >::type metadataJSON(metadataJSONSEXP);
    r_UpdateVector(colID, id, vector, dim, metadataJSON);
    return R_NilValue;
END_RCPP
}
// r_UpdateVectorIfVersion
void r_UpdateVectorIfVersion(int colID, std::string id, NumericVector vector, int dim, std::string metadataJSON, double expectedVersion);
RcppExport SEXP _libravdb_r_UpdateVectorIfVersion(SEXP colIDSEXP, SEXP idSEXP, SEXP vectorSEXP, SEXP dimSEXP, SEXP metadataJSONSEXP, SEXP expectedVersionSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type colID(colIDSEXP);
    Rcpp::traits::input_parameter< std::string >::type id(idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vector(vectorSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< std::string >::type metadataJSON(metadataJSONSEXP);
    Rcpp::traits::input_parameter< double >::type expectedVersion(expectedVersionSEXP);
    r_UpdateVectorIfVersion(colID, id, vector, dim, metadataJSON, expectedVersion);
    return R_NilValue;
END_RCPP
}
// r_DeleteVector
void r_DeleteVector(int colID, std::string id);
RcppExport SEXP _libravdb_r_DeleteVector(SEXP colIDSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type colID(colIDSEXP);
    Rcpp::traits::input_parameter< std::string >::type id(idSEXP);
    r_DeleteVector(colID, id);
    return R_NilValue;
END_RCPP
}
// r_GetVector
String r_GetVector(int colID, std::string id);
RcppExport SEXP _libravdb_r_GetVector(SEXP colIDSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type colID(colIDSEXP);
    Rcpp::traits::input_parameter< std::string >::type id(idSEXP);
    rcpp_result_gen = Rcpp::wrap(r_GetVector(colID, id));
    return rcpp_result_gen;
END_RCPP
}
// r_QueryVector
String r_QueryVector(int colID, NumericVector vector, int dim, int limit, std::string filterJSON);
RcppExport SEXP _libravdb_r_QueryVector(SEXP colIDSEXP, SEXP vectorSEXP, SEXP dimSEXP, SEXP limitSEXP, SEXP filterJSONSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type colID(colIDSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type vector(vectorSEXP);
    Rcpp::traits::input_parameter< int >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type limit(limitSEXP);
    Rcpp::traits::input_parameter< std::string >::type filterJSON(filterJSONSEXP);
    rcpp_result_gen = Rcpp::wrap(r_QueryVector(colID, vector, dim, limit, filterJSON));
    return rcpp_result_gen;
END_RCPP
}
// r_ScanCollection
String r_ScanCollection(int colID, int offset, int limit);
RcppExport SEXP _libravdb_r_ScanCollection(SEXP colIDSEXP, SEXP offsetSEXP, SEXP limitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type colID(colIDSEXP);
    Rcpp::traits::input_parameter< int >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< int >::type limit(limitSEXP);
    rcpp_result_gen = Rcpp::wrap(r_ScanCollection(colID, offset, limit));
    return rcpp_result_gen;
END_RCPP
}
// r_DatabaseQuery
String r_DatabaseQuery(int dbID, std::string sql);
RcppExport SEXP _libravdb_r_DatabaseQuery(SEXP dbIDSEXP, SEXP sqlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type dbID(dbIDSEXP);
    Rcpp::traits::input_parameter< std::string >::type sql(sqlSEXP);
    rcpp_result_gen = Rcpp::wrap(r_DatabaseQuery(dbID, sql));
    return rcpp_result_gen;
END_RCPP
}
// r_DatabaseQueryWithParams
String r_DatabaseQueryWithParams(int dbID, std::string sql, std::string paramsStr);
RcppExport SEXP _libravdb_r_DatabaseQueryWithParams(SEXP dbIDSEXP, SEXP sqlSEXP, SEXP paramsStrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type dbID(dbIDSEXP);
    Rcpp::traits::input_parameter< std::string >::type sql(sqlSEXP);
    Rcpp::traits::input_parameter< std::string >::type paramsStr(paramsStrSEXP);
    rcpp_result_gen = Rcpp::wrap(r_DatabaseQueryWithParams(dbID, sql, paramsStr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_libravdb_r_OpenDB", (DL_FUNC) &_libravdb_r_OpenDB, 1},
    {"_libravdb_r_CloseDB", (DL_FUNC) &_libravdb_r_CloseDB, 1},
    {"_libravdb_r_Ping", (DL_FUNC) &_libravdb_r_Ping, 1},
    {"_libravdb_r_SetGlobalMemoryLimit", (DL_FUNC) &_libravdb_r_SetGlobalMemoryLimit, 2},
    {"_libravdb_r_Vacuum", (DL_FUNC) &_libravdb_r_Vacuum, 1},
    {"_libravdb_r_DropDatabase", (DL_FUNC) &_libravdb_r_DropDatabase, 1},
    {"_libravdb_r_ListCollections", (DL_FUNC) &_libravdb_r_ListCollections, 1},
    {"_libravdb_r_CreateCollection", (DL_FUNC) &_libravdb_r_CreateCollection, 3},
    {"_libravdb_r_GetCollection", (DL_FUNC) &_libravdb_r_GetCollection, 2},
    {"_libravdb_r_GetCollectionCount", (DL_FUNC) &_libravdb_r_GetCollectionCount, 1},
    {"_libravdb_r_InsertVector", (DL_FUNC) &_libravdb_r_InsertVector, 5},
    {"_libravdb_r_UpdateVector", (DL_FUNC) &_libravdb_r_UpdateVector, 5},
    {"_libravdb_r_UpdateVectorIfVersion", (DL_FUNC) &_libravdb_r_UpdateVectorIfVersion, 6},
    {"_libravdb_r_DeleteVector", (DL_FUNC) &_libravdb_r_DeleteVector, 2},
    {"_libravdb_r_GetVector", (DL_FUNC) &_libravdb_r_GetVector, 2},
    {"_libravdb_r_QueryVector", (DL_FUNC) &_libravdb_r_QueryVector, 5},
    {"_libravdb_r_ScanCollection", (DL_FUNC) &_libravdb_r_ScanCollection, 3},
    {"_libravdb_r_DatabaseQuery", (DL_FUNC) &_libravdb_r_DatabaseQuery, 2},
    {"_libravdb_r_DatabaseQueryWithParams", (DL_FUNC) &_libravdb_r_DatabaseQueryWithParams, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_libravdb(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
